// react/renderlist/src/components/Ad/ad.jsx
import React from "react";
import s from "./ad.module.css";

function Ad({name, imgLink, price, roomsCount, liveSquare, floor, type }) {
  return (
    <div className={s.cont} >
      <div className={s.c2}>
        <img src={imgLink} alt="" />
      </div>
      <div className={s.c2}>
        <div>заголовок: {name}</div>
        <div>цена: {price}$</div>
        <div>комнат: {roomsCount}</div>
        <div>
          жилплощадь: {liveSquare} / этажей: {floor}
        </div>
        <div>тип: {type}</div>
      </div>
    </div>
  );
}

export default Ad;

// angular/input/1/src/app/ad/ad.component.ts
import { Component, Input } from '@angular/core';
import { EstateInterface } from '../estateInterface';

@Component({
  selector: 'app-ad',
  standalone: false,
  templateUrl: './ad.component.html',
  styleUrl: './ad.component.css'
})
export class AdComponent {
  @Input() estateUnit?: EstateInterface;
}

<div class="cont">
    <div class="c2">
        <img src="{{estateUnit?.imgLink}}" alt="">
    </div>
    <div class="c2">
        <div>цена: {{estateUnit?.price}}$</div>
        <div>комнат: {{estateUnit?.roomsCount}}</div>
        <div>жилплощадь: {{estateUnit?.liveSquare}} / этажей: {{estateUnit?.floor}}</div>
        <div>тип: {{estateUnit?.type}}</div>
    </div>
</div>
